[package]
name = "csv-attest"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[example]]
name = "csv_attest_demo"
path = "examples/csv_attest_demo.rs"

[dependencies]
csv-attest-sys = { workspace = true }
anyhow.workspace = true
thiserror.workspace = true
cc-eventlog.workspace = true
serde.workspace = true
serde_json.workspace = true
fs-err.workspace = true
num_enum.workspace = true
rand = "0.8"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"